### ISSUE TITLE
Unable to register memory (register_mr_buffers:465)

### ISSUE THREAD

**Issue by chaoyanghe** [aws/aws-ofi-nccl#70]
I was stuck with this problem for many days. May I know how to debug such issues?

Currently, I am using all_to_all NCCL MPI (world_size=64) + EFA. The error is as follows:
https://github.com/NVIDIA/nccl/issues/563 (NCCL engineer is not sure what's the problem and needs EFA's help)

**Comment by chaoyanghe** [comment]
```
10.0.87.143: 10.0.95.41: FI_HMEM_SYSTEMiov.iov_len = 134217728
10.0.87.143: 10.0.89.236: FI_HMEM_SYSTEMiov.iov_len = 134217728
10.0.87.143: 10.0.95.41: FI_HMEM_SYSTEMiov.iov_len = 134217728
10.0.87.143: 10.0.89.236: ip-10-0-89-236:3236:3428 [6] NCCL INFO Channel 06 : 8[160] -> 62[1c0] [receive] via NET/AWS Libfabric/2/Shared
10.0.87.143: 10.0.89.236: ip-10-0-89-236:3236:3428 [6] NCCL INFO Channel 06 : 62[1c0] -> 52[1a0] [send] via NET/AWS Libfabric/0/Shared
10.0.87.143: 10.0.95.41: ip-10-0-95-41:3231:3426 [2] NCCL INFO Channel 06 : 20[1a0] -> 10[180] [receive] via NET/AWS Libfabric/2/Shared
10.0.87.143: 10.0.95.41: ip-10-0-95-41:3231:3426 [2] NCCL INFO Channel 06 : 10[180] -> 0[160] [send] via NET/AWS Libfabric/0/Shared
10.0.87.143: 10.0.78.113:
10.0.87.143: 10.0.78.113: ip-10-0-78-113:3234:3425 [5] register_mr_buffers:469 NCCL WARN NET/OFI Unable to register memory (type = 1) for device 0. RC: -736476143, Error:
10.0.87.143: 10.0.78.113: ip-10-0-78-113:3234:3425 [5] NCCL INFO include/net.h:23 -> 2
10.0.87.143: 10.0.78.113: ip-10-0-78-113:3234:3425 [5] NCCL INFO transport/net.cc:223 -> 2
10.0.87.143: 10.0.78.113: ip-10-0-78-113:3234:3425 [5] NCCL INFO transport.cc:111 -> 2
10.0.87.143: 10.0.78.113: ip-10-0-78-113:3234:3425 [5] NCCL INFO group.cc:137 -> 2 [Async thread]
10.0.87.143: 10.0.78.113: ip-10-0-78-113:3234:3234 [5] NCCL INFO group.cc:210 -> 2
10.0.87.143: 10.0.78.113: Traceback (most recent call last):
10.0.87.143: 10.0.78.113:   File "main_moe.py", line 199, in <module>
10.0.87.143: 10.0.78.113:     main()
10.0.87.143: 10.0.78.113:   File "main_moe.py", line 170, in main
10.0.87.143: 10.0.78.113:     output = model(x)
10.0.87.143: 10.0.78.113:   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
10.0.87.143: 10.0.78.113:     return forward_call(*input, **kwargs)
10.0.87.143: 10.0.78.113:   File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/distributed.py", line 801, in forward
10.0.87.143: 10.0.78.113:     output = self.module(*inputs, **kwargs)
10.0.87.143: 10.0.78.113:   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
10.0.87.143: 10.0.78.113:     return forward_call(*input, **kwargs)
10.0.87.143: 10.0.78.113:   File "/home/deepspeed/.local/lib/python3.6/site-packages/moe_layer/model/standard_moe_model.py", line 44, in forward
10.0.87.143: 10.0.78.113:     h = self.moe_layer(hidden_states)
10.0.87.143: 10.0.78.113:   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
10.0.87.143: 10.0.78.113:     return forward_call(*input, **kwargs)
10.0.87.143: 10.0.78.113:   File "/home/deepspeed/.local/lib/python3.6/site-packages/moe_layer/model/switch_transformer_layers.py", line 169, in forward
10.0.87.143: 10.0.78.113:     expert_inputs = _AllToAll.apply(self.process_group, torch.cat(route_inputs))
10.0.87.143: 10.0.78.113:   File "/home/deepspeed/.local/lib/python3.6/site-packages/moe_layer/model/switch_transformer_layers.py", line 25, in forward
10.0.87.143: 10.0.78.113:     dist.all_to_all_single(output, input, group=group)
10.0.87.143: 10.0.78.113:   File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 2386, in all_to_all_single
10.0.87.143: 10.0.78.113:     work = group.alltoall_base(output, input, output_split_sizes, input_split_sizes, opts)
10.0.87.143: 10.0.78.113: RuntimeError: NCCL error in: /tmp/pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:38, unhandled system error, NCCL version 21.0.3
10.0.87.143: 10.0.78.113: ncclSystemError: System call (socket, malloc, munmap, etc) failed.
10.0.87.143: 10.0.87.143:
10.0.87.143: 10.0.87.143: ip-10-0-87-143:3311:3501 [6] register_mr_buffers:469 NCCL WARN NET/OFI Unable to register memory (type = 1) for device 1. RC: 1848411153, Error:
10.0.87.143: 10.0.87.143: ip-10-0-87-143:3311:3501 [6] NCCL INFO include/net.h:23 -> 2
10.0.87.143: 10.0.87.143: ip-10-0-87-143:3311:3501 [6] NCCL INFO transport/net.cc:223 -> 2
10.0.87.143: 10.0.87.143: ip-10-0-87-143:3311:3501 [6] NCCL INFO transport.cc:111 -> 2
10.0.87.143: 10.0.87.143: ip-10-0-87-143:3311:3501 [6] NCCL INFO group.cc:137 -> 2 [Async thread]
10.0.87.143: 10.0.87.143: ip-10-0-87-143:3311:3311 [6] NCCL INFO group.cc:210 -> 2
```

**Comment by chaoyanghe** [comment]
FI_HMEM_SYSTEMiov.iov_len = 134217728 (128G)

This means the memory allocation is 128G 

```

static ncclResult_t register_mr_buffers(ofiComm_t *comm, void *data,
					int size, int type,
					struct fid_mr **mr_handle)
{
	ncclResult_t ret = ncclSuccess;
	int rc;
	struct fi_mr_attr mr_attr = {0};
	struct iovec iov = {0};

	/* Check if provider requires registration of local buffers */
	if ((local_mr != true) && (type == NCCL_PTR_HOST)) {
		NCCL_OFI_TRACE(NCCL_INIT | NCCL_NET,
			"Skip registering host buffer. local_mr: %d", local_mr);
		goto exit;
	}

	/* Check if provider requires registration of cuda device buffers */
	if ((hmem_mr != true) && (type == NCCL_PTR_CUDA)) {
		NCCL_OFI_TRACE(NCCL_INIT | NCCL_NET,
			"Skip registering CUDA buffer. hmem_mr: %d", hmem_mr);
		goto exit;
	}

	/* Populate IOV vector for memory registration */
	iov.iov_base = data;
	iov.iov_len = size;

	/* Initialize MR attributes */
	mr_attr.mr_iov = &iov;
	mr_attr.iov_count = 1;
	mr_attr.access = FI_SEND | FI_RECV;

	if (type == NCCL_PTR_HOST) {
	    printf("FI_HMEM_SYSTEM");
		mr_attr.iface = FI_HMEM_SYSTEM;
	} else {
	    printf("FI_HMEM_CUDA");
		mr_attr.iface = FI_HMEM_CUDA;

		/* Get CUDA device ID */
		ret = get_cuda_device(data, &mr_attr.device.cuda);
		if (OFI_UNLIKELY(ret != ncclSuccess)) {
			goto exit;
		}
	}

    **printf("iov.iov_len = %lu\n", iov.iov_len);**

	rc = fi_mr_regattr(nccl_ofi_component[comm->dev]->domain,
			    &mr_attr, 0, mr_handle);
	if (OFI_UNLIKELY(rc != 0)) {
		NCCL_OFI_WARN("Unable to register memory (type = %d) for device %d. RC: %d, Error: %s",
			       type, comm->dev, fi_strerror(-rc));
		ret = ncclSystemError;
	}

exit:
	return ret;
}

```

**Comment by chaoyanghe** [comment]
this issue is finally resolved by setting `NCCL_BUFFSIZE=2097152`.

**Comment by chaoyanghe** [comment]
```
[hchaoyan@ip-10-0-87-143]/fsx/hchaoyan/home/m5/src/MoELayer/scripts/docker% grep -o -i 10.0.95.41:\ FI_HMEM_SYSTEMiov.iov_len log/p3dn_alltoall_efa.log | wc -l 
930
```

all_to_all() operation requires too many connection with remote ranks. PyTorch ncclAlltoall() is implemented by ncclSend/ncclRecv for all ranks (world_size). 

```
2 (send/recv) *
64-8 (connection for remote GPUs) / GPU *
8 GPUs/node
= 896
```
